eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8011/eureka/
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1435;databaseName=SPRING_MICRO_JDBC
    username: sa
    password: password@123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
   show-sql: true
   hibernate.ddl-auto: update
